### ISSUE TITLE
Amigo drops items in simulated storing groceries challenge

### ISSUE THREAD

**Issue by fibonatic** [tue-robotics/tue_robocup#554] opened 2018-01-23 19:02 UTC
When running the storing groceries challenge in the simulator amigo always drops the item in its right hand when trying to place in the bookcase. And after two items have been placed on the second shelf from the bottom also the left hand always drops the item when placing:
```
[ERROR] [1516733524.066644976]: There is no goal which meets the given constraints. Planning will always fail to this goal constraint.
[ERROR] [1516733524.066719613]: Received position constraint: frame: /map
constraint: (x-3.280482)^2+(y-2.505137)^2 > 0.463516^2 and (x-3.280482)^2+(y-2.505137)^2 < 0.613516^2

[ERROR] [1516733524.067191]: Global planner couldn't plan a path to the specified constraints. Are the constraints you specified valid?
[ERROR] [1516733524.129940354]: There is no goal which meets the given constraints. Planning will always fail to this goal constraint.
[ERROR] [1516733524.129973433]: Received position constraint: frame: /map
constraint: (x-3.341482)^2+(y-2.505137)^2 > 0.463516^2 and (x-3.341482)^2+(y-2.505137)^2 < 0.613516^2

[ERROR] [1516733524.130226]: Global planner couldn't plan a path to the specified constraints. Are the constraints you specified valid?
[ERROR] [1516733524.188770561]: There is no goal which meets the given constraints. Planning will always fail to this goal constraint.
[ERROR] [1516733524.188799592]: Received position constraint: frame: /map
constraint: (x-3.341482)^2+(y-2.655137)^2 > 0.463516^2 and (x-3.341482)^2+(y-2.655137)^2 < 0.613516^2

[ERROR] [1516733524.189147]: Global planner couldn't plan a path to the specified constraints. Are the constraints you specified valid?
[ERROR] [1516733524.241727053]: There is no goal which meets the given constraints. Planning will always fail to this goal constraint.
[ERROR] [1516733524.241773234]: Received position constraint: frame: /map
constraint: (x-3.341482)^2+(y-2.805137)^2 > 0.463516^2 and (x-3.341482)^2+(y-2.805137)^2 < 0.613516^2

[ERROR] [1516733524.242136]: Global planner couldn't plan a path to the specified constraints. Are the constraints you specified valid?
[ERROR] [1516733524.292867524]: There is no goal which meets the given constraints. Planning will always fail to this goal constraint.
[ERROR] [1516733524.292896379]: Received position constraint: frame: /map
constraint: (x-3.341482)^2+(y-2.909137)^2 > 0.463516^2 and (x-3.341482)^2+(y-2.909137)^2 < 0.613516^2

[ERROR] [1516733524.293156]: Global planner couldn't plan a path to the specified constraints. Are the constraints you specified valid?
[ERROR] [1516733524.349338296]: There is no goal which meets the given constraints. Planning will always fail to this goal constraint.
[ERROR] [1516733524.349399088]: Received position constraint: frame: /map
constraint: (x-3.191482)^2+(y-2.909137)^2 > 0.463516^2 and (x-3.191482)^2+(y-2.909137)^2 < 0.613516^2

[ERROR] [1516733524.349656]: Global planner couldn't plan a path to the specified constraints. Are the constraints you specified valid?
[INFO] [1516733524.562412]: Placing
[ERROR] [1516733537.888925]: grasp precompute goal failed: 
{'frameStamped': pos:(x=0.642150913183, y=-0.229840123705, z=0.501), rot:(r=0.0, p=0.0, y=0.0) @ /amigo/base_link, 'pre_grasp': True, 'self': Arm(side='right'), 'allowed_touch_objects': [], 'timeout': 10, 'first_joint_pos_only': False}
[INFO] [1516733537.889320]: Retrying preplace
[ERROR] [1516733551.101732]: grasp precompute goal failed: 
{'frameStamped': pos:(x=0.617150913183, y=-0.229840123705, z=0.501), rot:(r=0.0, p=0.0, y=0.0) @ /amigo/base_link, 'pre_grasp': True, 'self': Arm(side='right'), 'allowed_touch_objects': [], 'timeout': 10, 'first_joint_pos_only': False}
[WARN] [1516733551.102332]: Cannot pre-place the object
[INFO] [1516733551.102899]: State machine terminating 'PUT':'failed':'failed'
[INFO] [1516733551.103817]: State machine starting in initial state 'LOCK_ARM' with userdata: 
	[]
[INFO] [1516733551.104298]: locking_designator 

Designator(
  lock = <bound method LockingDesignator.lock of LockingDesignator(None)>
  lockable = <bound method LockingDesignator.lockable of LockingDesignator(None)>
  name = None
  resolve_type = <class 'robot_skills.arms.Arm'>
  to_be_locked = 

Designator(
  all_arms = {'right': Arm(side='right')}
  available = <bound method ArmDesignator.available of Designator(resolve_type=<class 'robot_skills.arms.Arm'>, name=None)>
  lockable = <bound method ArmDesignator.lockable of Designator(resolve_type=<class 'robot_skills.arms.Arm'>, name=None)>
  name = None
  preferred_arm = Arm(side='right')
  resolve_type = <class 'robot_skills.arms.Arm'>)


  unlock = <bound method LockingDesignator.unlock of LockingDesignator(None)>)

 is now locked to Arm(side='
[INFO] [1516733551.104716]: State machine transitioning 'LOCK_ARM':'locked'-->'SPINDLE_MEDIUM'
[INFO] [1516733551.116612]: State machine transitioning 'SPINDLE_MEDIUM':'done'-->'MOVE_HUMAN_HANDOVER_JOINT_GOAL'
[INFO] [1516733553.153869]: State machine transitioning 'MOVE_HUMAN_HANDOVER_JOINT_GOAL':'succeeded'-->'SAY_OPEN_GRIPPER'
[INFO] [1516733553.154357]: 'Watch out, I will open my gripper in one second. Please take it from me.'
[INFO] [1516733559.626656]: State machine transitioning 'SAY_OPEN_GRIPPER':'spoken'-->'OPEN_GRIPPER_HANDOVER'
[ERROR] [1516733559.627281]: send_gripper_goal open is called but there is still an entity with id '9c02f3e2f0d10e9226ed5897a18c4f9e' occupying the gripper, please update the world model and remove this entity
[INFO] [1516733560.332366]: State machine transitioning 'OPEN_GRIPPER_HANDOVER':'succeeded'-->'SAY_CLOSE_NOW_GRIPPER'
[INFO] [1516733560.333024]: 'I will close my gripper now'
[INFO] [1516733562.782317]: State machine transitioning 'SAY_CLOSE_NOW_GRIPPER':'spoken'-->'CLOSE_GRIPPER_HANDOVER'
```

**Comment by MatthijsBurgh** [comment] 2018-03-04 11:08
I would this is caused by the difficult location of the bookshelf in our lab. No priority for now, so closing it.

**Closed by MatthijsBurgh** 2018-03-04 11:08 UTC
Labels: Storing groceries, bug
